export interface Application {
    idApplication?: number; // Optional because it's auto-generated by the backend
    score: number;
    submissionDate?: Date; // Optional because it's set by the backend
    availability: Date;
    fieldofStudy: string;
    status?: string; // Optional because it's set by the backend
    university: string;
    coverLetter: string;
    cv: string;
    offer: { idOffer: number 
      title :string
    }; // Relationship to the Offer entity
    userId?: number;
    applicantName?: string; // <-- new field for full name
  }